[package]
name = "ShelbyNewsletter"
version = "0.1.0"
authors = []

[addresses]
newsletter = "0x059302e333eb4300c4a9c656bcb848beb05cdcdfe2345c3c159a3aa16ccd591c"
shelby_newsletter = "0x059302e333eb4300c4a9c656bcb848beb05cdcdfe2345c3c159a3aa16ccd591c"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-node-v1.14.0"
subdir = "aptos-move/framework/aptos-framework"